# Generated by Django 5.1.7 on 2025-06-01 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    def insertData(self, schema_editor):
        Group = self.get_model('auth', 'Group')

        administrador = Group(name="Administrador")
        administrador.save()

        cliente = Group(name="Cliente")
        cliente.save()


    operations = [
        migrations.RunPython(insertData, atomic=True),
    ]